<?php
$title = 'Update Warlog';
$this->headTitle($title);
?>
<div class="content shadow">
    <div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
<?php
$form->setAttribute('action', $this->url('warlog', ['action' => 'upload']));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
if (isset($errors)) {
    if (array_key_exists('wins', $errors)) {
        echo '<div class="form-group has-error has-feedback">';
        echo $this->formLabel($form->get('wins')->setLabelAttributes(['class' => 'control-label']));
        echo $this->formText($form->get('wins')->setAttribute('class', 'form-control'));
        echo '<span class="glyphicon glyphicon-remove form-control-feedback" 
            aria-hidden="true"></span>';
        echo '<p>Must be a number</p>';

    } else {
        echo '<div class="form-group has-success has-feedback">';
        echo $this->formLabel($form->get('wins')->setLabelAttributes(['class' => 'control-label']));
        echo $this->formText($form->get('wins')->setAttribute('class', 'form-control'));
        echo '<span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>';
    }
} else {
    echo '<div class="form-group">';
    echo $this->formLabel($form->get('wins')->setLabelAttributes(['class' => 'control-label']));
    echo $this->formText($form->get('wins')->setAttribute('class', 'form-control'));
}
echo '</div>';

if (isset($errors)) {
    if (array_key_exists('losses', $errors)) {
        echo '<div class="form-group has-error has-feedback">';
        echo $this->formLabel($form->get('losses')->setLabelAttributes(['class' => 'control-label']));
        echo $this->formText($form->get('losses')->setAttribute('class', 'form-control'));
        echo '<span class="glyphicon glyphicon-remove form-control-feedback" 
            aria-hidden="true"></span>';
        echo '<p>Must be a number</p>';

    } else {
        echo '<div class="form-group has-success has-feedback">';
        echo $this->formLabel($form->get('losses')->setLabelAttributes(['class' => 'control-label']));
        echo $this->formText($form->get('losses')->setAttribute('class', 'form-control'));
        echo '<span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>';
    }
} else {
    echo '<div class="form-group">';
    echo $this->formLabel($form->get('losses')->setLabelAttributes(['class' => 'control-label']));
    echo $this->formText($form->get('losses')->setAttribute('class', 'form-control'));
}
echo '</div>';

if (isset($errors)) {
    if (array_key_exists('draws', $errors)) {
        echo '<div class="form-group has-error has-feedback">';
        echo $this->formLabel($form->get('draws')->setLabelAttributes(['class' => 'control-label']));
        echo $this->formText($form->get('draws')->setAttribute('class', 'form-control'));
        echo '<span class="glyphicon glyphicon-remove form-control-feedback" 
            aria-hidden="true"></span>';
        echo '<p>Must be a number</p>';

    } else {
        echo '<div class="form-group has-success has-feedback">';
        echo $this->formLabel($form->get('draws')->setLabelAttributes(['class' => 'control-label']));
        echo $this->formText($form->get('draws')->setAttribute('class', 'form-control'));
        echo '<span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>';
    }
} else {
    echo '<div class="form-group">';
    echo $this->formLabel($form->get('draws')->setLabelAttributes(['class' => 'control-label']));
    echo $this->formText($form->get('draws')->setAttribute('class', 'form-control'));
}
echo '</div>';

if (isset($errors)) {
    if (array_key_exists('file', $errors)) {
        echo '<div class="form-group has-error has-feedback">';
        echo $this->formLabel($form->get('file')->setLabelAttributes(['class' => 'control-label']));
        echo $this->formFile($form->get('file')->setAttribute('class', 'form-control'));
        echo '<span class="glyphicon glyphicon-remove form-control-feedback"
            aria-hidden="true"></span>';
        echo '<p>No valid image file</p>';
    }
}
else {
    echo '<div class="form-group">';
    echo $this->formLabel($form->get('file')->setLabelAttributes(['class' => 'control-label']));
    echo $this->formFile($form->get('file')->setAttribute('class', 'form-control'));
}
?>
<br />
<div class="form-group">
<?php
echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-success'));
echo $this->form()->closeTag();
?>
</div>
</div>
