<?php
$title = 'Current War';
$this->headTitle($title);
?>
<div class="content shadow">
    <div class="page-header">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <?php
    $form->setAttribute('action', $this->url('warclaim', ['action' => 'detail']));
    $form->setAttribute('class', 'form-horizontal');
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo '<div class="form-group">';
    echo $this->formLabel($form->get('strategy')->setLabelAttributes(['class' => 'control-label col-sm-2']));
    echo '<div class="col-sm-10">';
    echo $this->formTextArea($form->get('strategy')->setAttribute(['readonly' => 'readonly']));
    echo '</div>';
    echo '</div>';
    for ($i = 0; $i < $size; $i++) {
        echo '<div class="form-group">';
        echo $this->formLabel($form->get($i)->setLabelAttributes(['class' => 'control-label col-sm-2']));
        echo '<div class="col-sm-10">';
        echo $this->formText($form->get($i)->setAttribute('class', 'form-control')->setAttribute('list', 'members'));
        echo '</div>';
        echo '</div>';
    }
    echo $this->form()->closeTag();
</div>
