<script>
var time = new Date().getTime();
$(document.body).bind("mousemove keypress", function(e) {
    time = new Date().getTime();
});

function refresh() {
    if(new Date().getTime() - time >= 120000) 
        window.location.reload(true);
    else 
        setTimeout(refresh, 10000);
}

setTimeout(refresh, 10000);
</script>
<?php
$title = 'Clanwar against ' . $warclaim->getOpponent();
$this->headTitle($title);
?>
<datalist id="members">
    <?php foreach($members as $member): ?>
    <option value="<?php echo $member->getName(); ?>" />
    <option value="<?php echo $member->getMini(); ?>" />
    <?php endforeach; ?>
</datalist>
<div class="content shadow">
    <div class="page-header">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <br />
    <?php
    $form->setAttribute('action', $this->url('warclaim', ['action' => 'current']));
    $form->setAttribute('class', 'form-horizontal');
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formHidden($form->get('size'));
    echo $this->formHidden($form->get('opponent'));
    if (isset($errors)) {
    if (array_key_exists('strategy', $errors)) {
    echo '<div class="form-group has-error has-feedback">';
        echo $this->formLabel($form->get('strategy')->setLabelAttributes(['class' => 'control-label col-sm-2']));
        echo '<div class="col-sm-10">';
            echo $this->formTextArea($form->get('strategy'));
            echo '<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>';
            echo '</div>';
        echo $this->formElementErrors($form->get('strategy'));
        } else {
        echo '<div class="form-group has-success has-feedback">';
            echo $this->formLabel($form->get('strategy')->setLabelAttributes(['class' => 'control-label col-sm-2']));
            echo '<div class="col-sm-10">';
                echo $this->formTextArea($form->get('strategy'));
                echo '</div>';
            echo '<span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>';
            }
            } else {
            echo '<div class="form-group">';
                echo $this->formLabel($form->get('strategy')->setLabelAttributes(['class' => 'control-label col-sm-2']));
                echo '<div class="col-sm-10">';
                    echo $this->formTextArea($form->get('strategy'));
                    echo '</div>';
                }
                echo '</div>';
            ?>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th class="col-xs-1">#</th>
                            <th class="col-xs-4 name">Assigned</th>
                            <th class="col-xs-4 name">Cleanup</th>
                            <th class="col-xs-3">Time mirror until attack</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        for ($i = 0; $i < $warclaim->getSize(); $i++) {
                        echo '<tr>';
                            if (isset($errors)) { 
                            if (array_key_exists($i, $errors) || array_key_exists($i . 'c', $errors) ||
                            array_key_exists($i . 'i', $errors)) {
                            echo '<td>';
                                echo $this->formLabel($form->get($i)->setLabelAttributes(
                                ['class' => 'control-label']
                                ));
                                echo '</td>';
                            echo '<td>';
                                echo $this->formSearch($form->get($i)->setAttribute('list', 'members'));
                                echo $this->formElementErrors($form->get($i));
                                echo '</td>';
                            echo '<td>';
                                echo $this->formSearch($form->get($i . 'c')->setAttribute('list', 'members'));
                                echo $this->formElementErrors($form->get($i . 'c'));
                                echo '</td>';
                            echo '<td>';
                                echo $this->formText($form->get($i . 'i'));
                                echo $this->formElementErrors($form->get($i . 'i'));
                                echo '</td>';

                            } else {
                            echo '<td>';
                                echo $this->formLabel($form->get($i)->setLabelAttributes(
                                ['class' => 'control-label']
                                ));
                                echo '</td>';
                            echo '<td>';
                                echo $this->formSearch($form->get($i)->setAttribute('list', 'members'));
                                echo '</td>';
                            echo '<td>';
                                echo $this->formSearch($form->get($i . 'c')->setAttribute('list', 'members'));
                                echo '</td>';
                            echo '<td>';
                                echo $this->formText($form->get($i . 'i'));
                                echo '</td>';
                            }
                            } else {
                            echo '<td>';
                                echo $this->formLabel($form->get($i)->setLabelAttributes(
                                ['class' => 'control-label']
                                ));
                                echo '</td>';
                            echo '<td>';
                                echo $this->formSearch($form->get($i)->setAttribute('list', 'members'));
                                echo '</td>';
                            echo '<td>';
                                echo $this->formSearch($form->get($i . 'c')->setAttribute('list', 'members'));
                                echo '</td>';
                            echo '<td>';
                                echo $this->formText($form->get($i . 'i'));
                                echo '</td>';
                            }
                            echo '</th>';
                        }
                        ?>
                    </tbody>
                </table>
            </div>
            <div class="form-group">
                <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-success')) ?>
                <?php if ($user->role > \Account\Model\Role::ELDER): ?>
                <a href="<?php echo $this->url('warclaim', ['action' => 'close', 'id' => $warclaim->getId()]); ?>" class="btn btn-danger">Close War</a>
                <?php endif; ?>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
