<?php
$title = 'Lost Password';
$this->headTitle($title);
?>
<div class="content shadow">
    <div class="page-header">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <?php
    $form->setAttribute('action', $this->url('account', ['action' => 'lostpassword']));
    $form->prepare();
    echo $this->form()->openTag($form);
    if (isset($errors)) {
        echo '<div class="form-group has-error has-feedback">';
        echo $this->formLabel($form->get('email')
                ->setLabelAttributes(['class' => 'control-label']));
        echo $this->formEmail($form->get('email')); 
        echo '<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>';
        echo $errors;
    } else {
        echo '<div class="form-group">';
        echo $this->formLabel($form->get('email')
            ->setLabelAttributes(['class' => 'control-label']));
        echo $this->formText($form->get('email')); 
    }
    echo '</div>';
    echo '<div class="form-group">';
    echo $this->formSubmit($form->get('submit'));
?>
</div>
<?php echo $this->form()->closeTag(); ?>
</div>
