<?php
$session = new \Zend\Session\Container('user');
$title = 'Profile';
$this->headTitle($title);
?>
<div class="container content shadow">
    <div class="row">
        <div class="col-md-3">
            <?php
            echo '<img src="' . $account->getAvatar() . '" class="img-responsive img-thumbnail
            "style="max-width:240px; max-height:260px;">';
            ?>
        </div>
        <div class="col-md-5">
            <h4>Profile</h4>
            <ul class="list-group">
                <li class="list-group-item"><?php echo $account->getName(); ?></li>
                <li class="list-group-item">Role: <?php echo Account\Model\Account::convertToRole($account->getRole()); ?></li>
                <li class="list-group-item">Registered Since: <?php echo substr($account->getDateRegistered(), 0, 10); ?></li>
            </ul>
        </div>
    </div>
    <?php if ($self) { ?>
    <div class="row">
        <div class="col-md-4">
            <h4>Account Settings</h4>
            <ul class="list-group">
                <li class="list-group-item"><a href="/account/uploadavatar">Change Avatar</a></li>
                <li class="list-group-item"><a href="/account/edit">Edit Profile</a></li>
            </ul>
        </div>
        <div class="col-md-4">
            <h4>Member Settings</h4>
            <ul class="list-group">
                <li class="list-group-item"><a href="#">Set Member Roles</a></li>
            </ul>
        </div>
        <div class="col-md-4">
            <h4>War Log</h4>
            <ul class="list-group">
                <li class="list-group-item"><a href="#">Update current Warlog</a></li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <h4>News</h4>
            <ul class="list-group">
                <li class="list-group-item"><a href="<?php echo $this->url('news', ['action' => 'add']); ?>">Add news</a></li>
            </ul>
        </div>
        <?php if ($session->role > 3) { 
            echo '<div class="col-md-4">';
            echo '<h4>Applications</h4>';
            echo '<ul class="list-group">';
            echo '<li class="list-group-item">';
            if($open_applications) {                    
                echo '<span class="badge badge-default">' . $open_applications . '</span> 
                        <a href="/applynow/overview">Application Overview</a>'; 
            } else {
                echo '<a href="/applynow/overview">Application Overview ';
            }
            echo '</li>';
            echo '</ul>';
            echo '</div>';
        } ?>
        </ul> 
        </div>
    </div>
    <?php } ?>
</div>
