<?php
$session = new \Zend\Session\Container('user');
$title = 'Profile';
$this->headTitle($title);
?>
<div class="col-md-2">
    <?php
    echo '<img src="' . $account->getAvatar() . '" class="img-responsive img-thumbnail
        "style="max-width:180px; max-height:200px;">';
    ?>
</div>
<div class="col-md-2">
    <h4>Profile</h4>
    <?php
    echo $account->getName() . '<br />';
    echo 'Role: ' . Account\Model\Account::convertToRole($account->getRole()) . '<br />';
    echo 'Registered Since:<br />' . substr($account->getDateRegistered(), 0, 10) . '<br />';
    ?>
</div>
<?php if ($self) { ?>
<div class="col-md-2">
    <h4>Account Settings</h4>
    <a href="/account/uploadavatar">Change Avatar</a><br/>
    <a href="/account/edit">Edit Profile</a><br/>
</div>
<div class="col-md-2">
    <h4>Member Settings</h4>
    <a href="#">Set Member Roles</a><br/>
</div>
<div class="col-md-2">
    <h4>War Log</h4>
    <a href="#">Update current Warlog</a><br/>
</div>
<div class="col-md-2">
    <h4>News</h4>
    <a href="<?php echo $this->url('news', ['action' => 'add']); ?>">Add news</a><br />
</div>
<div class="col-md-2">
    <h4>Guides</h4>
    <a href="#">Add Guide</a><br/>
    <a href="#">Edit Guide</a><br/>
    <a href="#">Delete Guide</a><br/>
</div>
<div class="col-md-2">
    <h4>WarClaim</h4>
    <a href="#">Start new War</a><br/>
    <a href="#">Edit current war</a><br/>
    <a href="#">End current war</a><br/>
</div>
<div class="col-md-2">
    <?php
    if ($session->role > 3) {
        echo '<h4>Applications</h4>';
        echo '<a href="/applynow/overview">Application Overview ';  
        if($open_applications) 
            echo '<span class="badge badge-default">' . $open_applications . '</span></a>'; 
    }
}
?>
</div>
