<?php
$session = new \Zend\Session\Container('user');
$title = 'Profile';
$this->headTitle($title);
?>
<div class="container content shadow">
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <a href="<?php echo $account->getAvatar(); ?>" class="thumbnail">
                <img src="<?php echo $account->getAvatar(); ?>" class="img-responsive img-thumbnail">
            </a>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
            <h4>Profile</h4>
            <ul class="list-group">
                <li class="list-group-item"><?php echo $account->getName(); ?></li>
                <li class="list-group-item">Role: 
                    <?php echo Account\Model\Role::convertToRole((int) $account->getRole()); ?></li>
                <?php if ($account->getMini()): ?>
                <li class="list-group-item">Mini-Account: <?php echo $account->getMini(); ?></li>
                <?php endif; ?>
                <li class="list-group-item">Registered Since: <?php echo substr($account->getDateRegistered(), 0, 10); ?></li>
            </ul>
        </div>
        <div class="clearfix visible-md visible-lg"></div>
        <?php if ($self): ?>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <h4>Account Settings</h4>
            <ul class="list-group">
                <li class="list-group-item"><a href="/account/edit/<?php echo $account->getId(); ?>">Edit Profile</a></li>
            </ul>
        </div>
        <?php if (\Account\Service\PermissionChecker::check(\Account\Model\Role::MEMBER)): ?>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <h4>Media</h4>
            <ul class="list-group">
                <li class="list-group-item"><a href="/media/add">Add Media</a></li>
            </ul>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <h4>Applications</h4>
            <ul class="list-group">
                <li class="list-group-item">
                    <?php if($open_applications): ?>
                    <span class="badge badge-default"><?php echo $open_applications; ?></span> 
                    <a href="/applynow/overview">Application Overview</a>
                    <?php else: ?>
                    <a href="/applynow/overview">Application Overview</a>
                    <?php endif; ?>
                </li>
            </ul>
        </div>
        <?php endif; ?>
        <div class="clearfix visible-md visible-lg"></div>
        <?php if (\Account\Service\PermissionChecker::check(\Account\Model\Role::ELDER)): ?>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <h4>News</h4>
            <ul class="list-group">
                <li class="list-group-item"><a href="<?php echo $this->url('news', ['action' => 'add']); ?>">Add news</a></li>
                <li class="list-group-item"><a href="<?php echo $this->url('newscategory'); ?>">Categories</a></li>
            </ul>
        </div>
        <?php endif; ?>
        <?php if (\Account\Service\PermissionChecker::check(\Account\Model\Role::CO)): ?>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <h4>User Settings</h4>
            <ul class="list-group">
                <li class="list-group-item"><a href="/admin/setroles">Set User Roles</a></li>
            </ul>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <h4>War Log</h4>
            <ul class="list-group">
                <li class="list-group-item"><a href="/warlog/upload">Update current Warlog</a></li>
            </ul>
        </div>
        <?php endif; ?>
        <div class="clearfix visible-md visible-lg"></div>
        <?php if (\Account\Service\PermissionChecker::check(\Account\Model\Role::MEMBER)): ?>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <h4>Warstatus</h4>
            <ul class="list-group">
                <li class="list-group-item">
                    <a href="/warstatus/edit">Set my Warstatus</a>
                </li>
                <li class="list-group-item">
                    <a href="/warstatus/index">Warstatus Overview</a>
                </li>
            </ul>
        </div>
        <?php endif; ?>
        <?php if (\Account\Service\PermissionChecker::check(\Account\Model\Role::MEMBER)): ?>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <h4>Warclaim</h4>
            <ul class="list-group">
                <?php if ($war): ?>
                <li class="list-group-item">
                    <a href="/warclaim/current">Current War</a>
                </li>
                <?php endif; ?>
                <?php if (\Account\Service\PermissionChecker::check(\Account\Model\Role::CO) && !$war): ?>
                <li class="list-group-item"><a href="/warclaim/precautions">Create New War</a></li>
                <?php endif; ?>
            </ul>
        </div>
    <?php endif; ?>
    <?php endif; ?>
</div>
