<?php

$title = 'Register';
$this->headTitle($title);
?>
<div class="content shadow">
    <div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <?php
    $form->setAttribute('action', $this->url('account', ['action' => 'register']));
    $form->prepare();
    echo $this->form()->openTag($form);
    if (isset($errors)) {
        if (array_key_exists('name', $errors)) {
            echo '<div class="form-group has-error has-feedback">';
            echo $this->formLabel(
                $form->get('name')
                    ->setLabelAttributes(['class' => 'control-label']));
            echo $this->formText(
                $form->get('name')
                    ->setAttribute('class', 'form-control'));
            echo '<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>';
            if ($errors['name'] === 'name_taken') {
                echo '<p>Username already taken. Please choose another</p>';
            } else {
                echo '<p>Username must be between 3 and 64 characters long and only contains characters, numbers, _ and -</p>';
            }
        } else {
            echo '<div class="form-group has-success has-feedback">';
            echo $this->formLabel(
                $form->get('name')
                    ->setLabelAttributes(['class' => 'control-label']));
            echo $this->formText(
                $form->get('name')
                    ->setAttribute('class', 'form-control'));
            echo '<span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>';
        }
    } else {
        echo '<div class="form-group">';
        echo $this->formLabel(
            $form->get('name')
                ->setLabelAttributes(['class' => 'control-label']));
        echo $this->formText(
            $form->get('name')
                ->setAttribute('class', 'form-control'));
    }
    ?>
</div>
<?php
if (isset($errors)) {
    if (array_key_exists('password', $errors)) {
        echo '<div class="form-group has-error has-feedback">';
        echo $this->formLabel(
            $form->get('password')
                ->setLabelAttributes(['class' => 'control-label']));
        echo $this->formPassword(
            $form->get('password')
                ->setAttribute('class', 'form-control'));
        echo '<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>';
        echo '<p>Password must be between 4 and 64 characters long</p>';
    } else {
        echo '<div class="form-group has-success has-feedback">';
        echo $this->formLabel(
            $form->get('password')
                ->setLabelAttributes(['class' => 'control-label']));
        echo $this->formPassword(
            $form->get('password')
                ->setAttribute('class', 'form-control'));
        echo '<span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>';
    }
} else {
    echo '<div class="form-group">';
    echo $this->formLabel(
        $form->get('password')
            ->setLabelAttributes(['class' => 'control-label']));
    echo $this->formPassword(
        $form->get('password')
            ->setAttribute('class', 'form-control'));
}
?>
</div>
<?php
if (isset($errors)) {
    if (array_key_exists('email', $errors)) {
        echo '<div class="form-group has-error has-feedback">';
        echo $this->formLabel(
            $form->get('email')
                ->setLabelAttributes(['class' => 'control-label']));
        echo $this->formText(
            $form->get('email')
                ->setAttribute('class', 'form-control'));
        echo '<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>';
        if ($errors['email'] === 'email_taken') {
            echo '<p>E-Mail already taken. Please choose another</p>';
        } else {
            echo '<p>No valid E-Mail adress</p>';
        }
    } else {
        echo '<div class="form-group has-success has-feedback">';
        echo $this->formLabel(
            $form->get('email')
                ->setLabelAttributes(['class' => 'control-label']));
        echo $this->formText(
            $form->get('email')
                ->setAttribute('class', 'form-control'));
        echo '<span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>';
    }
} else {
    echo '<div class="form-group">';
    echo $this->formLabel(
        $form->get('email')
            ->setLabelAttributes(['class' => 'control-label']));
    echo $this->formText(
        $form->get('email')
            ->setAttribute('class', 'form-control'));
}
?>
</div>
<div class="form-group">
    <?php echo $this->formSubmit(
        $form->get('submit')
            ->setAttribute('class', 'btn btn-success'));
    ?>
</div>
</div>
<?php echo $this->form()->closeTag(); ?>
