<?php

$title = 'Register';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('account', ['action' => 'register']));
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?php echo $this->formLabel(
        $form->get('name')
            ->setLabelAttributes(['class' => 'control-label']));
    ?>
    <?php echo $this->formText(
        $form->get('name')
            ->setAttribute('class', 'form-control'));
    ?>
</div>
<div class="form-group">
    <?php echo $this->formLabel(
        $form->get('password')
            ->setLabelAttributes(['class' => 'control-label']));
    ?>
    <?php echo $this->formPassword(
        $form->get('password')
            ->setAttribute('class', 'form-control'));
    ?>
</div>
<div class="form-group">
    <?php echo $this->formLabel(
        $form->get('email')
            ->setLabelAttributes(['class' => 'control-label']));
    ?>
    <?php echo $this->formText(
        $form->get('email')
            ->setAttribute('class', 'form-control')
            ->setAttribute('rows', '10'));
    ?>
</div>
<div class="form-group">
    <?php echo $this->formSubmit(
        $form->get('submit')
            ->setAttribute('class', 'btn btn-success'));
    ?>
</div>
<?php echo $this->form()->closeTag(); ?>
