<?php
$title = 'Upload Avatar';
$this->headTitle($title);
?>
<div class="col-md-6">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('account',
    ['action' => 'uploadavatar']));
$form->prepare();
echo $this->form()->openTag($form);
if (isset($errors)) {
    if (array_key_exists('file', $errors)) {
        echo '<div class="form-group has-error has-feedback">';
        echo $this->formLabel($form->get('file')->setLabelAttributes(['class' => 'control-label']));
        echo $this->formFile($form->get('file')->setAttribute('class', 'form-control'));
        echo '<span class="glyphicon glyphicon-remove form-control-feedback"
            aria-hidden="true"></span>';
        echo '<p>No valid image file</p>';
    }
}
else {
    echo '<div class="form-group">';
    echo $this->formLabel($form->get('file')->setLabelAttributes(['class' => 'control-label']));
    echo $this->formFile($form->get('file')->setAttribute('class', 'form-control'));
}
?>
<br />
<div class="form-group">
<?php
echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-success'));
echo $this->form()->closeTag();
?>
</div>
