<?php
$title = 'Add Category';
$this->headTitle($title);
?>
<div class="content shadow">
    <div class"page-header">
        <h1><?php $this->escapeHtml($title); ?></h1>
    </div>
    <?php
    $form->setAttribute('action', $this->url('newscategory', ['action' => 'add']));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    foreach ($form as $element) {
        if (
            !($element instanceof Zend\Form\Element\Hidden) &&
            !($element instanceof Zend\Form\Element\Submit)) {

            if (isset($errors)) {
                if (array_key_exists($element->getName(), $errors)) {
                    echo '<div class="form-group has-error has-feedback">';
                    echo $this->formLabel($form->get($element->getName())->setLabelAttributes(['class' => 'control-label']));
                    echo $this->formElement($element);
                    echo '<span class="glyphicon glyphicon-remove form-control-feedback" 
                            aria-hidden="true"></span>';

                    echo $this->formElementErrors($element);
                } else {
                    echo '<div class="form-group has-success has-feedback">';
                    echo $this->formLabel($form->get($element->getName())->setLabelAttributes(['class' => 'control-label']));
                    echo $this->formElement($element);
                    echo '<span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>';
                }
            } else {
                echo '<div class="form-group">';
                echo $this->formLabel($form->get($element->getName())->setLabelAttributes(['class' => 'control-label']));
                echo $this->formElement($element);
            }
            echo '</div>';
        }
    }
    echo '<div class="form-group">';
    echo $this->formSubmit($form->get('submit'));
    echo '</div>';
    echo $this->form()->closeTag();
?>
</div>
