<?php
$title = 'Delete News Category';
$this->headTitle($title);
?>
<div class="content shadow">
    <div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>

    <p>Are you sure that you want to delete the 
        '<?php echo $this->escapeHtml($nc->getName()); ?>'
        category?
    </p>
    <?php
    $url = $this->url('newscategory', [
        'action' => 'delete',
        'id'     => $id,
    ]);
    ?>
    <form action="<?php echo $url; ?>" method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo (int) $nc->getId(); ?>"/>
            <input type="submit" class="btn btn-danger" name="del" value="Yes"/>
            <input type="submit" class="btn btn-primary" name="del" value="No"/>
        </div>
    </form>
</div>
