<?php

$title = 'Set User Roles';
$this->headTitle($title);
?>
<div class="content shadow" >
    <div class="page-header">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <?php
    $form->setAttribute('action', $this->url('admin', ['action' => 'setroles']));
    $form->setAttribute('method', 'get');
    $form->prepare();
    echo $this->form()->openTag($form);
    foreach ($form as $element) {
        if (!($element instanceof Zend\Form\Element\Submit)) {
            echo '<div class="form-group">';
            echo $this->formLabel($form->get($element->getName())->setLabelAttributes(
                [
                    'class' => 'control-label'
                ]
            ));
            echo $this->formElement($element);
            echo '</div>';
        }
    }
    echo '<div class="form-group">';
    echo $this->formSubmit($form->get('submit'));
    echo '</div>';
    echo $this->form()->closeTag();
    ?>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Current Role</th>
                    <th>New Role</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($users as $user): ?>
                <tr>
                    <th><?php echo $user->getName(); ?></th>
                    <th><?php echo Account\Model\Role::convertToRole((int) $user->getRole()); ?></th>
                    <form action="/admin/updaterole" method="POST">
                        <div class="form-group">
                            <input type="hidden" name="id" value="<?php echo $user->getId(); ?>">
                            <th>
                                <select class="form-control" name="select">
                                    <?php foreach ($role_strings as $role) {
                                    echo '<option value="' . $role . '" '; 
                                    if ($role == (int) $user->getRole()) echo 'selected';
                                    echo '>' . Account\Model\Role::convertToRole($role) . '</option>';
                                    }?>
                                </select>
                            </th>
                            <th><button type="submit" class="btn btn-default btn-sm">Confirm</button></th>
                    </form>
                    <th>
                        <?php if ($user->getRole() < \Account\Model\Role::MEMBER): ?>
                        <a href="<?php echo $this->url('admin',
                            [
                                'action' => 'delete', 
                                'id' => $user->getId()
                            ]);?>" class="btn btn-danger">Delete</a>
                        <?php endif; ?>
                    </th>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php echo $this->paginationControl($this->users, 'sliding', [
        'partial/paginator_setroles.phtml',
        'application',
    ],
    [
        'route' => 'setroles',
    ]);
    ?>
    <a href="<?php echo $this->url('account', ['action' => 'profile']);?>" class="btn btn-danger">Back</a>
    </div>

