<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return [
    'modules'                 => [
        'Account',
        'Application',
        'ApplyNow',
        'AppMail',
        'Members',
        'News',
        'Impressum',
        'Warlog',
        'Warclaim',
        'Media',
        'Warstatus',
    ],
    'module_listener_options' => [
        'module_paths'      => [
            './module',
            './vendor',
        ],
        'config_glob_paths' => [
            'config/autoload/{,*.}{global,local}.php',
        ],
    ],
];
