<?php
echo $this->doctype();
$session = new \Zend\Session\Container('user');
?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle(' - Eternal Deztiny'); ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink([
        'rel'  => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', ['conditional' => 'lt IE 9',])
        ->prependFile($this->basePath('js/html5shiv.js'), 'text/javascript', ['conditional' => 'lt IE 9',]); ?>

</head>
<body>
<nav role="navigation" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/img/logo.png" class="pull-left"><img src="/img/logo.png"></a>
            <a href="/news" class="navbar-brand">Eternal Deztiny</a>
        </div>
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="/news">News</a></li>
                <li><a href="/members">Members</a></li>
                <li><a href="/warlog">Warlog</a></li>
                <li><a href="#">Guides</a></li>
                <li><a href="#">Forum</a></li>
                <?php
                if (isset($session->role)) {
                    if ($session->role > 1) {
                        echo '<li><a href="#">WarClaim</a></li>';
                    } else {
                        echo '<li><a href="/applynow">Apply Now</a></li>';
                    }
                } else {
                    echo '<li><a href="/applynow">Apply Now</a></li>';
                }
                ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php if (isset($session->avatar)) {
                    echo '<li><img src="' . $session->avatar . '" class="img-responsive img-circle" style="max-width:75px; max-height:50px;"></li>';
                }
                if (isset($session->name)) {
                echo '<li><a href = "/account/profile/' . $session->name . '">' . $session->name . '</a></li>';
                echo '<li><a href = "/account/logout"> Logout</a></li>';
                } else {
                    echo '<li><a href = "/account/login"> Login</a></li>';
                    echo '<li><a href = "/account/register"> Register</a></li>';
                }
                ?>
            </ul>
        </div>
    </div>
</nav>
<div>
    <div class="container">
        <div class="col-xs-0 col-md-1"></div>
        <div class="col-xs-12 col-md-10 main">
            <?php echo $this->content; ?>
        </div>
        <div class="col-xs-0 col-md-1"></div>
    </div>
        <footer><a href = "/impressum">Impressum</footer>
</div>
</body>
</html>
