<?php
$title = 'Warstatus Overview';
$this->headTitle('Warstatus Overview');
?>
<div class="content shadow">
    <div class"page-header">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <br />
    <u>Currently <b><?php echo $in_war; ?></b> Member(s) available for war</u>
    <br />
    <br />
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Time until opt-in</th>
                    <th>Reason</th>
                    <th>Gemable</th>
                    <th>Crusade</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($accounts as $_ => $account): ?>
                <tr>
                    <th>
                        <?php echo $account['name']; ?>
                    </th>
                    <th>
                        <?php if ($account['duration']): ?>
                        <?php echo $account['duration']; ?> day(s) left 
                        <?php else: ?>
                        Opted-In
                        <?php endif; ?>
                    </th>
                    <th>
                        <?php if ($account['duration']): ?>
                        <?php echo $account['reason']; ?>
                        <?php endif; ?>
                    </th>
                    <th>
                        <?php if ($account['gemable']): ?>
                        <img src="/img/warstatus/gem.png" class="img-responsive warstatus-gem">
                        <?php else: ?>
                        <img src="/img/warstatus/no_gem.png" class="img-responsive warstatus-gem">
                        <?php endif; ?>
                    </th>
                    <th>
                        <?php if ($account['crusade']): ?>
                        <img src="/img/warstatus/crusade.png" class="img-responsive warstatus-crusade">
                        <?php else: ?>
                        <img src="/img/warstatus/no_crusade.png" class="img-responsive warstatus-crusade">
                        <?php endif; ?>
                    </th>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <a href="<?php echo $this->url('account', ['action' => 'profile']);?>" class="btn btn-danger">Back</a>
</div>
