<?php
$parsedown = new News\Service\Parsedown();
$title = $news->getTitle();
$this->headTitle($title);
?> 
<div class="content shadow">
    <div class="page-header">
        <h1><?php echo $news->getTitle(); ?></h1>
            by <a href="<?php echo $this->url('account', [
                'action' => 'profile', 
                'id' => $news->getAuthor(),
            ]); ?>"><?php echo $news->getAuthor(); ?></a>
        </h1>
    </div>
    <div class="page-header">
        <div class="row">
            <div class="col-md-2 visible-md visible-lg">
                <img src="/news_cat/<?php echo $news->getCategory(); ?>.png" 
                    class="news-cat-img">
            </div>
            <div class="col-md-10">
                <p>
                    <?php 
                        echo $parsedown->text(nl2br($news->getContent())); 
                    ?>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-10">
                <?php
                    if ($news->getAuthor() == $accountName) {
                        echo '<a href="' . $this->url('news', [
                            'action' => 'edit', 
                            'id' => $news->getId()
                        ]) . '">Edit</a>';
                echo "\t";
                echo '<a href="' . 
                    $this->url('news', [
                        'action' => 'delete', 
                        'id' => $news->getId()
                    ]) . '">Delete</a>';
                }
                ?>
            </div>
        </div>
    </div>
    <br />
    <?php
    foreach ($comments as $comment): ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href="<?php echo $this->url(
                    'account', [
                        'action' => 'profile',
                        'id' => $comment->getAccountName()
                    ]
                    ); ?>"><?php echo $comment->getAccountName() ?></a>
                    commented on 
                    <?php echo substr($comment->getDatePosted(), 0, -3); ?>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-2 visible-md visible-lg comment-border">
                        <img src="<?php echo $comment->getAccountPic(); ?>" class="news-cat-img">
                    </div>
                    <div class="col-md-10">
                        <p>
                            <?php 
                                echo $parsedown->text(nl2br($comment->getContent())); 
                            ?>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    <?php
    if ($accountName):
        $form->setAttribute('action', $this->url('news', [
            'action' => 'detail',
            'id' => $news->getId(),
        ]));
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('news_id'));
        echo $this->formHidden($form->get('account_id'));
        echo $this->formHidden($form->get('date_posted'));
        foreach ($form as $element):
            if (!($element instanceof Zend\Form\Element\Submit) &&
                !($element instanceof Zend\Form\Element\Hidden)):
                if (isset($errors)):
                    echo '<div class="form-group has-error has-feedback">';
                    echo $this->formElement($element);
                    echo '<span class="glyphicon glyphicon-remove 
                        form-control-feedback" aria-hidden="true"></span>';
                    echo $this->formElementErrors($element);
                else:
                    echo '<div class="form-group">';
                    echo $this->formElement($element);
                endif;
                echo '</div>';
            endif;
        endforeach;
        ?>
        <div class="form-group">
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
        <?php echo $this->form()->closeTag(); 
    else: ?>
        <p><b>You need to be logged in to comment.</b></p>
    <?php endif; ?>
</div>

