<?php

$title = 'Edit News';
$this->headTitle($title);
?>
<div class="content shadow">
    <div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>

    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url(
        'news',
        [
            'action' => 'edit',
            'id'     => $this->id,
        ]
    ));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formHidden($form->get('account_id')->setValue($accountId));
    ?>
    <div class="form-group">
        <?php echo $this->formLabel(
            $form->get('title')
                ->setLabelAttributes(['class' => 'control-label']));
        echo $this->formText($form->get('title'));
        ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel(
            $form->get('category_id')->setLabelAttributes(['class' => 'control-label']));
        echo $this->formSelect($form->get('category_id'));
        ?>
    </div>
    <div class="form-group">
        <?php 
        echo $this->formLabel(
            $form->get('content')
            ->setLabelAttributes(['class' => 'control-label']));
        echo $this->formTextarea($form->get('content'));
        if ($this->error && $this->error === 'tooLong') {
            echo '<p>Words for text must be smaller than 100 characters and the text only contains between 10
            and 100000 characters.</p>';
        }

        ?>
    </div>
    <div class="form-group">
        <?php echo $this->formSubmit(
            $form->get('submit')
                ->setAttribute('class', 'btn btn-success')); ?>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>
