<?php

$title = 'Edit News';
$this->headTitle($title);
?>
<div class="content shadow">
    <div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>

    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url(
        'news',
        [
            'action' => 'edit',
            'id'     => $this->id,
        ]
    ));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formHidden($form->get('account_id')->setValue($accountId));
    ?>
    <div class="form-group">
        <?php echo $this->formLabel(
            $form->get('title')
                ->setLabelAttributes(['class' => 'control-label']));
        echo $this->formText(
            $form->get('title')
                ->setAttribute('class', 'form-control'));
        ?>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel(
            $form->get('content')
                ->setLabelAttributes(['class' => 'control-label']));
        echo $this->formTextarea(
            $form->get('content')
                ->setAttribute('class', 'form-control')
                ->setAttribute('rows', '10'));
        if ($this->error && $this->error === 'tooLong') {
            echo '<p> A word in the text is too long.</p>';
        }

        ?>
    </div>
    <div class="form-group">
        <?php echo $this->formSubmit(
            $form->get('submit')
                ->setAttribute('class', 'btn btn-success')); ?>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>
