<?php

$title = 'News';
?>
    <?php $this->headTitle($title); ?>
    <?php foreach ($paginator as $item) : ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title"><?php echo $item->getTitle(); ?></h1>
                by <?php echo '<a href="' . 
                $this->url('account', ['action' => 'profile', 'id' => $item->getAuthor()]) . '">' . 
                $item->getAuthor() . '</a>'; ?>
            </div>
            <div class="panel-body">
                <p><?php echo $this->escapeHtml($item->getContent()); ?></p>
                <?php
                if ($item->getAuthor() == $accountName) {
                    echo '<a href="' . $this->url('news', ['action' => 'edit', 'id' => $item->getId()]) . '">Edit</a>';
                    echo "\t";
                    echo '<a href="' . $this->url('news', ['action' => 'delete', 'id' => $item->getId()]) . '">Delete</a>';
                }
                ?>
            </div>
            <div class="panel-footer">
                posted on <?php echo substr($item->getDatePosted(), 0, -3); ?>
            </div>
        </div>
    <?php endforeach; ?>
    <?php
    echo $this->paginationControl($this->paginator, 'sliding', ['partial/paginator.phtml', 'application'],
        [
            'route' => 'news'
        ]
    );
    ?>
