<?php
$parsedown = new News\Service\Parsedown();
$title = 'News';
$this->headTitle($title); 
?>
    <?php foreach ($paginator as $item) : ?>
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h1 class="panel-title"><?php echo $item->getTitle(); ?></h1>
                by <?php echo '<a href="' . 
                $this->url('account', ['action' => 'profile', 'id' => $item->getAuthor()]) . 
                '" class="panel-href">' . 
                $item->getAuthor() . '</a>'; ?>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-2 visible-md visible-lg news-border"> 
                        <img src="/news_cat/<?php echo $item->getCategory(); ?>.png" class="news-cat-img">
                    </div>
                    <div class="col-md-10">
                        <p><?php echo $parsedown->text(nl2br($item->getContent())); ?></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2 visible-md visible-lg news-border">
                        </div>
                        <div class="col-md-10">
                    <?php
                    if ($item->getAuthor() == $accountName) {
                        echo '<a href="' . $this->url('news', ['action' => 'edit', 'id' => $item->getId()]) . '">Edit</a>';
                        echo "\t";
                        echo '<a href="' . $this->url('news', ['action' => 'delete', 'id' => $item->getId()]) . '">Delete</a>';
                    }
                    ?>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="left-align col-xs-8 col-md-6">posted on <?php echo substr($item->getDatePosted(), 0, -3); ?></div>
                    <div class="right-align col-xs-4 col-md-6"><a href="
                        <?php 
                            echo $this->url('news', 
                                [
                                    'action' => 'detail', 
                                    'id' => $item->getId(),
                                    ]); ?>"><?php echo $item->getCommentCount(); ?> Comments</a></div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    <?php
    echo $this->paginationControl($this->paginator, 'sliding', ['partial/paginator.phtml', 'application'],
        [
            'route' => 'news'
        ]
    );
    ?>
