<?php $title = 'Members'; ?>
<div class="content shadow">
    <?php $this->headTitle($title); ?>
    <div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Role</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($members as $member) : ?>
            <tr>
            <th>
                <?php echo '<a href="' . 
                $this->url('account', ['action' => 'profile', 'id' => $member['name']]) . '">' . 
                $member['name'] . '</a>'; ?>
                </th>
                <th><?php echo $member['role']; ?></th>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
