<?php $title = 'Members'; ?>
<div class="content shadow">
    <?php $this->headTitle($title); ?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Role</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($members as $member) : ?>
            <tr>
                <th><?php echo $member['name']; ?></th>
                <th><?php echo $member['role']; ?></th>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
