<?php

/**
 * Generated by ZF2ModuleCreator
 */

namespace AppMail;

use Zend\ModuleManager\Feature\AutoloaderProviderInterface;
use Zend\ModuleManager\Feature\ConfigProviderInterface;
use Zend\Db\TableGateway\TableGateway;
use Zend\Db\ResultSet\ResultSet;

use AppMail\Model\AppMail;
use AppMail\Model\AppMailTable;

class Module implements AutoloaderProviderInterface, ConfigProviderInterface
{
    public function getAutoloaderConfig()
    {
        return array(
            'Zend\Loader\ClassMapAutoloader' => array(
                __DIR__ . '/autoload_classmap.php',
            ),
            'Zend\Loader\StandardAutoloader' => array(
                'namespaces' => array(
                    __NAMESPACE__ => __DIR__ . '/src/' . __NAMESPACE__,
                ),
            ),
        );
    }

    public function getConfig()
    {
        return include __DIR__ . '/config/module.config.php';
    }

    public function getServiceConfig()
    {
        return array(
            'factories' => array(
                'AppMail\Model\AppMailTable' =>  function($sm) {
                    $tableGateway = $sm->get('AppMailTableGateway');
                    $table = new AppMailTable($tableGateway);
                    return $table;
                },
                'AppMailTableGateway' => function ($sm) {
                    $dbAdapter = $sm->get('Zend\Db\Adapter\Adapter');
                    $resultSetPrototype = new ResultSet();
                    $resultSetPrototype->setArrayObjectPrototype(new AppMail());
                    return new TableGateway('app_mail', $dbAdapter, null, $resultSetPrototype);
                },
            ),
        );
    }
}