<?php
$title = 'Delete Media';
$this->headTitle($title);
?>
<div class="content shadow">
    <div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>

    <p>Are you sure that you want to delete
        '<?php echo $this->escapeHtml($media->getTitle()); ?>' by
        '<?php echo $this->escapeHtml($media->getAuthor()); ?>'?
    </p>
    <?php
    $url = $this->url('media', [
        'action' => 'delete',
        'id'     => $id,
    ]);
    ?>
    <form action="<?php echo $url; ?>" method="post">
        <div>
            <input type="hidden" name="id" value="<?php echo (int)$media->getId(); ?>"/>
            <input type="submit" class="btn btn-danger" name="del" value="Yes"/>
            <input type="submit" class="btn btn-primary" name="del" value="No"/>
        </div>
    </form>
</div>
