<?php

$title = 'Edit Media';
$this->headTitle($title);
?>
<div class="content shadow">
    <div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>

    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url(
        'media',
        [
            'action' => 'media',
            'id'     => $this->id,
        ]
    ));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formHidden($form->get('account_id')->setValue($accountId));
    if (isset($errors)) {
        if (array_key_exists('title', $errors)) {
            echo '<div class="form-group has-error has-feedback">';
            echo $this->formLabel($form->get('title')->setLabelAttributes(['class' => 'control-label']));
            echo $this->formText($form->get('title')->setAttribute('class', 'form-control'));
            echo '<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>';
            echo '<p>Title must be between 5 and 100 characters long.</p>';
        } else {
            echo '<div class="form-group has-success has-feedback">';
            echo $this->formLabel($form->get('title')->setLabelAttributes(['class' => 'control-label']));
            echo $this->formText($form->get('title')->setAttribute('class', 'form-control'));
            echo '<span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>';
        }
    } else {
        echo '<div class="form-group">';
        $this->formLabel($form->get('title')->setLabelAttributes(['class' => 'control-label']));
        echo $this->formText($form->get('title')->setAttribute('class', 'form-control'));
    }
    ?>
    </div>
    <?php
    if (isset($errors)) {
        if (array_key_exists('title', $errors)) {
            echo '<div class="form-group has-error has-feedback">';

            echo '<div class="form-group">';
            <?php echo $this->formLabel($form->get('url')->setLabelAttributes(['class' => 'control-label']));
            echo $this->formText($form->get('url')->setAttribute('class', 'form-control');
            echo '<p>Must be a valid youtube url.</p>';
        } else {
            echo '<div class="form-group has-success has-feedback">';
            echo $this->formLabel($form->get('title')->setLabelAttributes(['class' => 'control-label']));
            echo $this->formText($form->get('title')->setAttribute('class', 'form-control'));
            echo '<span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>';
        }
    } else {
        echo '<div class="form-group">';
        $this->formLabel($form->get('title')->setLabelAttributes(['class' => 'control-label']));
        echo $this->formText($form->get('title')->setAttribute('class', 'form-control'));
    }
    ?>
    </div>
    <div class="form-group">
    <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-success')); ?>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>
