<?php $title = 'Live'; ?>
<div class="content shadow">
    <?php $this->headTitle($title); ?>
    <div class="page-header">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="row">
        <div class="embed-responsive embed-responsive-16by9 col-xs-8">
            <iframe class="embed-responsive-item" src="http://www.twitch.tv/noob__pwnisher/embed" frameborder="0" scrolling="no"></iframe>
        </div>
        <div class="embed-responsive embed-responsive-16by9 col-xs-4">
            <iframe class="embed-responsive-item" src="http://www.twitch.tv/noob__pwnisher/chat?popout=" frameborder="0" scrolling="no"></iframe>
        </div>
    </div>
</div>
