<?php
$title = 'Home';
$this->headTitle($title);
?>

<div class="content shadow">
    <div class="jumbotron">
        <a href="/img/ed.jpg" class="thumbnail">
            <img src="/img/ed.jpg" class="img-responsive img-thumbnail">
        </a>
        <h1>Welcome to Eternal Deztiny</h1>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>About us</h3>
        </div>
        <div class="panel-body">
            <ul>
                <li>We are a 21+ only adult clan that is organized and very serious about wars</li>
                <li>We have active, engaging conversations and fast donations (troop lvl 6+)</li>
                <li><a href="/warlog">A pretty good war record</a></li>
                <li>We have GroupMe chats for better communication and for sharing base/strategy/anything else you fancy</li>
                <li>We have members from all over the world who love some CoC</li>
            </ul>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Recruiting Criteria</h3>
        </div>
        <div class="panel-body">
            <ul>
                <li>Serious players who love to win wars and collaborate with teammates with non-rushed bases</li>
                <li>TH6s who are heading to TH7</li>
                <li>TH7 with dragon unlocked (lvl 2 preferred)</li>
                <li>TH8 with lvl 3 dragon</li>
                <li>TH8.5/9 who's defense match their offense</li>
            </ul>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Clan Dynamics</h3>
        </div>
        <div class="panel-body">
            <ul>
                <li>All our members are experienced in their townhall level and more than willing to give advice and feedback to help you learn and grow</li>
                <li>Our donations are super fast and we always donate what you want/need whether it's for farming or practicing war comp attacks</li>
                <li>We are very active, and outside of war we're pretty chill as well (war is chill too, but more serious). We love to joke around and have fun.</li>
                <li>Our wars are usually 30-40 people so you will get a feel of the larger war dynamics without feeling super lost</li>
            </ul>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>What are you waiting for? Apply!</h3>
        </div>
        <div class="panel-body">
            <ul>
                <li>Either fill out an <a href="/applynow">Application</a> here or visit us in game at #28PU922</li>
                <li>We will get back to you as soon as we can (usually within a few hours but no more than 24 hours) if you apply through the website</li>
                <li>If you apply in game, please state that you read about us on our website and that you understand our <a href="/applynow">rules</a></li>
            </ul>
        </div>
    </div>
</div>
