<?php
$title = 'Home';
$this->headTitle($title);
?>

<div class="content shadow">
    <div class="jumbotron">
        <a href="/img/ed.jpg" class="thumbnail">
            <img src="/img/ed.jpg" class="img-responsive img-thumbnail">
        </a>
        <h1>Welcome to Eternal Deztiny</h1>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>About us</h3>
        </div>
        <div class="panel-body">
            <ul>
                <li>
                    We are a 21+ adult clan, highly organized, serious about 
                    wars and constantly striving for perfection.
                </li>
                <li>
                    <a href="/warlog">Great War Record</a>(95% Effectivity Rate)
                </li>
                <li>
                    We have very active members from all over the world, engaging 
                    conversations and fast donations.
                </li>
                <li>
                    We use GroupMe App for better communication, strategy talk and anything else you fancy.
                </li>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Recruiting Criteria</h3>
        </div>
        <div class="panel-body">
            <ul>
                <li>
                    We are looking for serious players who love to win wars and 
                    work towards learning and perfecting their attacks.
                </li>
                <li>
                    TH9 whose offense matches or exceeds their defense.
                </li>
                <li>
                    TH8 with Lv. 4 Hogs or Lv. 3 Dragons.
                </li>
                <li>
                    TH7 with dragon unlocked (Lv. 2 preferred).
                </li>
                <li>
                    TH6s who are close to TH7.
                </li>
                <li>
                    No Rushed Bases.
                </li>
            </ul>

        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Clan Dynamics</h3>
        </div>
        <div class="panel-body">
            <ul>
                <li>
                    All our members are always willing to give advice and 
                    feedback to help you learn and grow.
                </li>
                <li>
                    Our donations are fast and we always donate what you want/need 
                    whether it's for farming, war attacks or practicing war strategies.
                </li>
                <li>
                    We're fun, chill and love to joke around. War is about fun 
                    too but we expect you to plan and bring your best out of 
                    respect for everyone else who does. 
                </li>
                <li>
                    Our wars usually include 30-40 people so you will get a feel 
                    of the larger war dynamics.
                </li>
            </ul>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>What are you waiting for? Apply!</h3>
        </div>
        <div class="panel-body">
            <ul>
                <li>Either fill out an <a href="/applynow">Application</a> here or visit us in game at #28PU922</li>
                <li>We will get back to you as soon as we can (usually within a few hours but no more than 24 hours) if you apply through the website</li>
                <li>If you apply in game, please state that you read about us on our website and that you understand our <a href="/applynow">rules</a></li>
            </ul>
        </div>
    </div>
</div>
