<?php
$title = 'Registered successfully!';
$this->headTitle($title);
?>
<div class="content shadow">
    <div class="page-header">
    <h2><?php echo $this->escapeHtml($title); ?></h2>
    </div>
    <p>You registered successfully, but your account needs to be activated. Please have a look at your inbox and
        follow the given link to activate your account.</p>
    <a href="/">Go back to Home</a>
</div>
