<?php
$title = 'Application Details';
$this->headTitle($title);
?>
<div class="content shadow">
<div class="page-header">
<h1><?php echo $this->escapeHtml($title); ?></h1>
</div>
<?php
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo '<div class="form-group">';
echo $this->formLabel($form->get('processed')->setLabelAttributes(['class' => 'control-label']));
$form_elem = $form->get('processed');
$form_elem->setAttribute('class', 'form-control');

$form_submit = $form->get('submit');
$form_submit->setAttribute('class', 'btn btn-success');
if ($role < Account\Model\Role::ELDER) {
    $form_elem->setAttribute('disabled', 'disabled');
    $form_submit->setAttribute('disabled', 'disabled');
}
echo $this->formSelect($form_elem);
echo '</div>';
echo '<div class="form-group">';
echo $this->formSubmit($form_submit);
echo '</div>';
echo '<div class="form-group">';
echo $this->formLabel($form->get('name')->setLabelAttributes(['class' => 'control-label']));
echo $this->formText($form->get('name')->setAttribute('class', 'form-control')->setAttribute('readonly', 'readonly'));
echo '</div>';
echo '<div class="form-group">';
echo $this->formLabel($form->get('tag')->setLabelAttributes(['class' => 'control-label']));
echo $this->formText($form->get('tag')->setAttribute('class', 'form-control')->setAttribute('readonly', 'readonly'));
echo '</div>';
echo '<div class="form-group">';
echo $this->formLabel($form->get('email')->setLabelAttributes(['class' => 'control-label']));
echo $this->formText($form->get('email')->setAttribute('class', 'form-control')->setAttribute('readonly', 'readonly'));
echo '</div>';
echo '<div class="form-group">';
echo $this->formLabel($form->get('age')->setLabelAttributes(['class' => 'control-label']));
echo $this->formText($form->get('age')->setAttribute('class', 'form-control')->setAttribute('readonly', 'readonly'));
echo '</div>';
echo '<div class="form-group">';
echo $this->formLabel($form->get('th')->setLabelAttributes(['class' => 'control-label']));
echo $this->formText($form->get('th')->setAttribute('class', 'form-control')->setAttribute('readonly', 'readonly'));
echo '</div>';
echo '<div class="form-group">';
echo $this->formLabel($form->get('warStars')->setLabelAttributes(['class' => 'control-label']));
echo $this->formText($form->get('warStars')->setAttribute('class', 'form-control')->setAttribute('readonly', 'readonly'));
echo '</div>';
echo '<div class="form-group">';
echo $this->formLabel($form->get('spoilsOfWar')->setLabelAttributes(['class' => 'control-label']));
echo $this->formText($form->get('spoilsOfWar')->setAttribute('class', 'form-control')->setAttribute('readonly', 'readonly'));
echo '</div>';
echo '<div class="form-group">';
echo $this->formLabel($form->get('goldGrab')->setLabelAttributes(['class' => 'control-label']));
echo $this->formText($form->get('goldGrab')->setAttribute('class', 'form-control')->setAttribute('readonly', 'readonly'));
echo '</div>';
echo '<div class="form-group">';
echo $this->formLabel($form->get('niceAndTidy')->setLabelAttributes(['class' => 'control-label']));
echo $this->formText($form->get('niceAndTidy')->setAttribute('class', 'form-control')->setAttribute('readonly', 'readonly'));
echo '</div>';
echo '<div class="form-group">';
echo $this->formLabel($form->get('infos')->setLabelAttributes(['class' => 'control-label']));
echo $this->formTextarea($form->get('infos')->setAttribute('class', 'form-control')
    ->setAttribute('rows', '10')->setAttribute('readonly', 'readonly'));
echo '</div>';
echo '<div class="form-group">';
echo $this->formLabel($form->get('why')->setLabelAttributes(['class' => 'control-label']));
echo $this->formTextarea($form->get('why')->setAttribute('class', 'form-control')
    ->setAttribute('rows', '10')->setAttribute('readonly', 'readonly'));
echo '</div>';
echo '<div class="form-group">';
echo $this->formLabel($form->get('strategies')->setLabelAttributes(['class' => 'control-label']));
echo $this->formTextarea($form->get('strategies')->setAttribute('class', 'form-control')
    ->setAttribute('rows', '10')->setAttribute('readonly', 'readonly'));
echo '</div>';
echo '<div class="form-group">';
echo $this->formLabel($form->get('basepic')->setLabelAttributes(['class' => 'control-label']));
echo '<br />';
echo '<a href="' . $form->get('basepic')->getValue() . '" class="thumbnail">';
echo '<img src="' . $form->get('basepic')->getValue() . '" class="img-responsive img-thumbnail">';
echo '</a>';
echo '</div>';
echo '<div class="form-group">';
echo $this->formLabel($form->get('profilepic')->setLabelAttributes(['class' => 'control-label']));
echo '<br />';
echo '<a href="' . $form->get('profilepic')->getValue() . '" class="thumbnail">';
echo '<img src="' . $form->get('profilepic')->getValue() . '" class="img-responsive img-thumbnail">';
echo '</a>';
echo '</div>';
echo $this->form()->closeTag();
?>
</div>

