<?php
$title = 'Apply Now';
$this->headTitle($title);
?>
<div class="content shadow">
    <div class="page-header">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <h2><em>Please read through our rules first. Before you apply.</em></h2>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="thumbnail">
                <img src="/img/applynow/mature.png">
                <div class="caption">
                    <h3>Matures only</h3>
                    <p>We have a general 18+ rule. If your application convinces us, we maybe do exceptions.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumbnail">
                <img src="/img/applynow/noloot.png">
                <div class="caption">
                    <h3>Never attack for loot</h3>
                    <p>Even if we already won, we want our members to do serious practice attacks and don't attack for loot<p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumbnail">
                <img src="/img/applynow/useboth.png">
                <div class="caption">
                    <h3>Always use both attack</h3>
                    <p>Even if we already won, we want our members to show activity and therefor use both attacks in every war. No exceuses.<p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
            <div class="col-md-4">
                <div class="thumbnail">
                    <img src="/img/applynow/cleanup.png">
                    <div class="caption">
                        <h3>Second attack is for cleanup</h3>
                        <p>Second attack is reserved for cleanup. Talk to an Elder or higher, for an appropiate cleanup target</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="thumbnail">
                    <img src="/img/applynow/three.png">
                    <div class="caption">
                        <h3>Attack +/- 3 your target</h3>
                        <p>If there is no cleanuo, the second attack is for practice. Your practice target should be in your range. Normally +/-3 your mirror on the war map.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="thumbnail">
                    <img src="/img/applynow/request.png">
                    <div class="caption">
                        <h3>No donation requirement</h3>
                        <p>We are pretty loose about donations. Request anything you need and donate what you can.</p>
                    </div>
                </div>
            </div>
        </div>
        <a href="/applynow/apply" type="button" class="btn btn-success">Read and understood.</a>
    </div>
</div>
