<?php
$title = 'Application Overview';
$this->headTitle($title);
?>
<div class="content shadow">
    <div class="page-header">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="alert alert-warning" role="alert">Open Applications</div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Tag</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($unprocessed as $item) : ?>
            <tr>
                <th>
                    <?php echo '<a href="' . $this->url('applynow', ['action' => 'detail', 'id' => $item->getId()]) . '">' .$item->getName() . '<a>'; ?>
                </th>
                <th> <?php echo '#' . $item->getTag(); ?></th>
                <th> 
                </th>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="alert alert-success" role="alert">Processed Applications</div>
    <div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name(Tag)</th>
                <th>Processed</th>
                <th>Send mail</th>

            </tr>
        </thead>
        <tbody>
            <?php foreach ($processed as $item) : ?>
            <tr>
                <th>
                    <?php echo '<a href="' . $this->url('applynow', ['action' => 'detail', 'id' => $item->getId()]) . '">' .$item->getName() . 
                         "\n" . '(#' . $item->getTag() . ')' . '<a>'; ?>
                </th>
                <th> <?php echo \ApplyNow\Model\statusToString((int) $item->getProcessed()) . ' by ' . $item->getAccountName();?></th>
                <?php if(($item->getProcessed() == \ApplyNow\Model\Status::ACCEPTED 
                || $item->getProcessed() == \ApplyNow\Model\Status::DECLINED)
                && $role > \Account\Model\Role::MEMBER) {
                echo '<th><a href="' . $this->url('applynow', ['action' => 'sendConfirmationMail', 
                        'id' => $item->getId()]) . '" class="btn btn-default btn-sm" >Send Mail</a>';
                    } else {
                    echo '<th><button type="button" class="btn btn-default btn-sm" disabled="disabled">Send Mail</a>';
                        } 
                        ?>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    </div>
    <?php echo $this->paginationControl($this->processed, 'sliding', 
    [
    'partial/paginator.phtml', 
    'application'
    ],
    [
    'route' => 'overview', 
    ]
    );
    ?>
</div>
