<?php
$title = 'Application Overview';
$this->headTitle($title);
?>
<div class="col-md-8">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="alert alert-warning" role="alert">Open Applications</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Tag</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($unprocessed as $item) : ?>
        <tr>
            <th> <?php echo $item->getName(); ?></th>
            <th> <?php echo $item->getTag(); ?></th>
            <th> 
            <?php echo '<a href="' . $this->url('applynow', ['action' => 'detail', 'id' => $item->getId()]) . '">Details </a>'; ?>
            </th>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<div class="alert alert-success" role="alert">Processed Applications</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Tag</th>
            <th>Processed</th>
            <th>Processed by</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($processed as $item) : ?>
        <tr>
            <th> <?php echo $item->getName(); ?></th>
            <th> <?php echo $item->getTag(); ?></th>
            <th> <?php echo \ApplyNow\Model\statusToString((int) $item->getProcessed()); ?></th>
            <th> <?php echo $item->getAccountName(); ?></th>
            <th> 
            <?php echo '<a href="' . $this->url('applynow', ['action' => 'detail', 'id' => $item->getId()]) . '">Details </a>'; ?>
            </th>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
</div>
