<?php
$title = 'Processing Application';
$this->headTitle($title);
?>
<div class="content shadow">
    <div class="page-header">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    Please don't close this tab, we're processing your application. You will be redirected
    afterwards.
    <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-success active" 
             role="progressbar" aria-valuenow="0" aria-valuemin="0" 
             aria-valuemax="0" style="width: 100%">
      </div>
    </div>
</div>

